### ISSUE TITLE
ProvisioningFailed

### ISSUE THREAD

**Issue by pschen** [OZEO-DOOZ/nrf_mesh_plugin#264]
I/flutter (32377): [NordicNrfMesh] calling disconnect without connected device..
D/BluetoothGatt(32377): connect() - device: 7C:DF:A1:C2:02:CE, auto: false
D/BluetoothGatt(32377): registerApp()
D/BluetoothGatt(32377): registerApp() - UUID=d386b758-2f37-4daf-8320-5587ad7d582c
D/BluetoothGatt(32377): onClientRegistered() - status=0 clientIf=10
I/flutter (32377): [NordicNrfMesh] received unexpected connection state update : ConnectionStateUpdate(deviceId: 7C:DF:A1:C2:02:CE, connectionState: DeviceConnectionState.connecting, failure: null)
D/BluetoothGatt(32377): onClientConnectionState() - status=0 clientIf=10 device=7C:DF:A1:C2:02:CE
I/flutter (32377): [NordicNrfMesh] received ConnectionStateUpdate(deviceId: 7C:DF:A1:C2:02:CE, connectionState: DeviceConnectionState.connected, failure: null)
D/BluetoothGatt(32377): discoverServices() - device: 7C:DF:A1:C2:02:CE
D/BluetoothGatt(32377): onConnectionUpdated() - Device=7C:DF:A1:C2:02:CE interval=6 latency=0 timeout=500 status=0
D/BluetoothGatt(32377): onSearchComplete() = Device=7C:DF:A1:C2:02:CE Status=0
I/flutter (32377): [BleMeshManager] services [DiscoveredService(serviceId: 00001801-0000-1000-8000-00805f9b34fb, characteristicIds: [00002a05-0000-1000-8000-00805f9b34fb], characteristics: [DiscoveredCharacteristic(characteristicId: 00002a05-0000-1000-8000-00805f9b34fb, serviceId: 00001801-0000-1000-8000-00805f9b34fb)], includedServices: []), DiscoveredService(serviceId: 00001800-0000-1000-8000-00805f9b34fb, characteristicIds: [00002a00-0000-1000-8000-00805f9b34fb, 00002a01-0000-1000-8000-00805f9b34fb, 00002aa6-0000-1000-8000-00805f9b34fb], characteristics: [DiscoveredCharacteristic(characteristicId: 00002a00-0000-1000-8000-00805f9b34fb, serviceId: 00001800-0000-1000-8000-00805f9b34fb), DiscoveredCharacteristic(characteristicId: 00002a01-0000-1000-8000-00805f9b34fb, serviceId: 00001800-0000-1000-8000-00805f9b34fb), DiscoveredCharacteristic(characteristicId: 00002aa6-0000-1000-8000-00805f9b34fb, serviceId: 00001800-0000-1000-8000-00805f9b34fb)], includedServices: []), DiscoveredService(serviceId: 00001827-0000-1000-8000-00805f9
D/BluetoothGatt(32377): configureMTU() - device: 7C:DF:A1:C2:02:CE mtu: 517
D/BluetoothGatt(32377): onConfigureMTU() - Device=7C:DF:A1:C2:02:CE mtu=23 status=0
I/flutter (32377): [NordicNrfMesh] connect took 1453ms
D/fr.dooz.nordic_nrf_mesh.DoozMeshProvisioningStatusCallbacks(32377): onProvisioningStateChanged 01a87112-3456-787c-dfa1-c202ce0000b1
D/fr.dooz.nordic_nrf_mesh.DoozMeshProvisioningStatusCallbacks(32377): meshNodeAlreadySaved false
D/fr.dooz.nordic_nrf_mesh.DoozMeshManagerCallbacks(32377): getMtu 20
D/fr.dooz.nordic_nrf_mesh.DoozMeshManagerCallbacks(32377): sendProvisioningPdu
D/BluetoothGatt(32377): onConnectionUpdated() - Device=7C:DF:A1:C2:02:CE interval=36 latency=0 timeout=500 status=0
D/BluetoothGatt(32377): setCharacteristicNotification() - uuid: 00002adc-0000-1000-8000-00805f9b34fb enable: true
V/MeshManagerApi(32377): Provisioning pdu sent: 0x030005
V/MeshManagerApi(32377): Provisioning pdu sent: 0x030005
V/MeshManagerApi(32377): Received provisioning message: 0x03010100010000000000000000
V/ProvisioningCapabilities(32377): Number of elements: 1
V/AlgorithmType(32377): Supported output oob action type: FIPS P-256 Elliptic Curve
V/ProvisioningCapabilities(32377): Public key information available: false
V/ProvisioningCapabilities(32377): Static OOB information available: : false
V/ProvisioningCapabilities(32377): Output OOB size: 0
V/ProvisioningCapabilities(32377): Input OOB size: 0
D/fr.dooz.nordic_nrf_mesh.DoozMeshProvisioningStatusCallbacks(32377): onProvisioningStateChanged 01a87112-3456-787c-dfa1-c202ce0000b1
D/fr.dooz.nordic_nrf_mesh.DoozMeshProvisioningStatusCallbacks(32377): meshNodeAlreadySaved true
V/MeshManagerApi(32377): Received provisioning message: 0x030903
D/fr.dooz.nordic_nrf_mesh.DoozMeshProvisioningStatusCallbacks(32377): onProvisioningFailed
E/flutter (32377): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Future already completed
E/flutter (32377): #0      _Completer.completeError (dart:async/future_impl.dart:15:31)
E/flutter (32377): #1      _provisioning.<anonymous closure> (package:nordic_nrf_mesh/src/utils/provisioning.dart:154:15)
E/flutter (32377): #2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
E/flutter (32377): #3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (32377): #4      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (32377): #5      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (32377): #6      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (32377): #7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (32377): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (32377): 
I/flutter (32377): [NordicNrfMesh] caught error during provisioning... NrfMeshProvisioningException(ProvisioningFailureCode.provisioningFailed, Failed to provision device 7C:DF:A1:C2:02:CE)
I/flutter (32377): [NordicNrfMesh] should cancel provisioning
D/fr.dooz.nordic_nrf_mesh.DoozMeshManagerCallbacks(32377): onNetworkUpdated
D/fr.dooz.nordic_nrf_mesh.DoozMeshManagerCallbacks(32377): onNetworkUpdated
D/BluetoothGatt(32377): refresh() - device: 7C:DF:A1:C2:02:CE
I/flutter (32377): [NordicNrfMesh] successfully assigned 3 to node !
I/flutter (32377): [NordicNrfMesh] successfully assigned 3 to node !
E/flutter (32377): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(NOT_FOUND, MeshNode with uuid 01a87112-3456-787c-dfa1-c202ce0000b1 doesn't exist, null, null)
E/flutter (32377): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter (32377): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
E/flutter (32377): <asynchronous suspension>
E/flutter (32377): #2      _provisioning.<anonymous closure> (package:nordic_nrf_mesh/src/utils/provisioning.dart:187:7)
E/flutter (32377): <asynchronous suspension>
E/flutter (32377): 
E/flutter (32377): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(NOT_FOUND, MeshNode with uuid 01a87112-3456-787c-dfa1-c202ce0000b1 doesn't exist, null, null)
E/flutter (32377): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter (32377): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
E/flutter (32377): <asynchronous suspension>
E/flutter (32377): #2      _provisioning.<anonymous closure> (package:nordic_nrf_mesh/src/utils/provisioning.dart:187:7)
E/flutter (32377): <asynchronous suspension>
E/flutter (32377): 
D/BluetoothGatt(32377): setCharacteristicNotification() - uuid: 00002adc-0000-1000-8000-00805f9b34fb enable: false
I/flutter (32377): [NordicNrfMesh] received ConnectionStateUpdate(deviceId: 7C:DF:A1:C2:02:CE, connectionState: DeviceConnectionState.disconnected, failure: null)
D/BluetoothGatt(32377): cancelOpen() - device: 7C:DF:A1:C2:02:CE
D/permissions_handler(32377): No permissions found in manifest for: []4
D/BluetoothGatt(32377): onClientConnectionState() - status=0 clientIf=10 device=7C:DF:A1:C2:02:CE
D/BluetoothGatt(32377): close()
D/BluetoothGatt(32377): unregisterApp() - mClientIf=10
D/BluetoothAdapter(32377): isLeEnabled(): ON
D/BluetoothLeScanner(32377): onScannerRegistered() - status=0 scannerId=10 mScannerId=0
I/flutter (32377): deviceUuid: 01a87112-3456-787c-dfa1-c202ce0000b1
D/BluetoothAdapter(32377): isLeEnabled(): ON

**Comment by Akhil-Sai-Prasad** [comment]
@pschen were you able to fix this issue?
